### ISSUE TITLE
GitHub is where people learn, share, and work together to build software.

### ISSUE THREAD

**Issue by ksiau** [Thestrangercamus/On-constitution-amendment-NO.1#32]
GitHub is where people learn, share, and work together to build software.

**Comment by jackbulusi** [comment]
把人逼到这里来说话 可悲、可怜、可叹，有本事你给他找块干净地儿 让他畅所欲言而不用喝茶

**Comment by shinkisan** [comment]
> 你的观点老掉牙而完全经不起推敲，你的问题在于你完全小看了天下人，说到底还是你学问不到家却好为人师、好高骛远、好大喜功。你不仅得不到有识之士的同情和认可，只能招来他们的冷嘲。
> 另外， GitHub is where people learn, share, and work together to build software. 我们不欢迎你在我们学习、研究、发展科技的地方发表无关科技的观点。



请您具体指出该用户违反了github哪一条用户协议，否则不要擅自代表github的立场，甚至进行人身攻击。
而且显然，github并不反对政治内容，可以参见github官方的【展示某些国家政府要求github删除政治相关内容的请求信】的项目gov-takedowns：[https://github.com/github/gov-takedowns](url)
然而github并不对这些内容执行删除，足以说明其立场。
楼主如果觉得愤怒，有两个办法可以选：
1.要求中国政府遵照宪法实行言论自由，这样作者自然就不会把内容发布到github。祝楼主成功。
2.给github写信要求github删除该内容。如果你自称是来自中国政府的委托，说不定你的信也可以被github官方光荣收录到【gov-takedowns】项目中。
如果不顺利建议楼主可以去用码云，我保证不会有这些内容。

**Comment by shinkisan** [comment]
> 
> 
> 把人逼到这里来说话 可悲、可怜、可叹，有本事你给他找块干净地儿 让他畅所欲言而不用喝茶

刚得到的消息，今天已经被请喝茶了

**Comment by sheltont** [comment]
GitHub就成了“你们”的了？一下子就把“我”代表了？说说你是如何推敲的？
